// MysteryShop Store Database - 200+ stores
const STORES = [
  // TECH
  { id: "adorama", name: "Adorama", slug: "adorama", category: "tech", description: "Professional photography, video, and audio equipment. One of the best camera and electronics retailers trusted by pros worldwide.", priceRange: "$10 – $5,000+", affiliate: "https://www.adorama.com/?utm_source=mysteryshop", tags: ["cameras", "electronics", "photography"] },
  { id: "newegg", name: "Newegg", slug: "newegg", category: "tech", description: "The go-to destination for PC components, laptops, gaming hardware, and consumer electronics at competitive prices.", priceRange: "$5 – $3,000+", affiliate: "https://www.newegg.com/?utm_source=mysteryshop", tags: ["computers", "pc parts", "electronics"] },
  { id: "b-and-h", name: "B&H Photo", slug: "b-and-h", category: "tech", description: "Massive selection of photography, video, audio, and tech gear. A legendary NYC retailer now serving the world online.", priceRange: "$15 – $10,000+", affiliate: "https://www.bhphotovideo.com/?utm_source=mysteryshop", tags: ["cameras", "audio", "video"] },
  { id: "micro-center", name: "Micro Center", slug: "micro-center", category: "tech", description: "America's favorite computer superstore with deep discounts on CPUs, GPUs, laptops, and accessories.", priceRange: "$10 – $4,000+", affiliate: "https://www.microcenter.com/?utm_source=mysteryshop", tags: ["computers", "pc parts", "laptops"] },
  { id: "anker", name: "Anker", slug: "anker", category: "tech", description: "Premium charging accessories, earbuds, cables, and power banks. Known for quality at a fair price.", priceRange: "$8 – $200", affiliate: "https://www.anker.com/?utm_source=mysteryshop", tags: ["chargers", "cables", "accessories"] },
  { id: "razer", name: "Razer", slug: "razer", category: "tech", description: "High-performance gaming peripherals, laptops, and accessories designed for serious gamers.", priceRange: "$20 – $4,000+", affiliate: "https://www.razer.com/?utm_source=mysteryshop", tags: ["gaming", "keyboards", "mice"] },
  { id: "corsair", name: "Corsair", slug: "corsair", category: "tech", description: "Top-tier PC components, gaming peripherals, and streaming gear loved by enthusiasts and pros.", priceRange: "$15 – $800", affiliate: "https://www.corsair.com/?utm_source=mysteryshop", tags: ["gaming", "pc parts", "peripherals"] },
  { id: "logitech", name: "Logitech", slug: "logitech", category: "tech", description: "The world's leading maker of mice, keyboards, webcams, and audio gear for work and play.", priceRange: "$10 – $400", affiliate: "https://www.logitech.com/?utm_source=mysteryshop", tags: ["mice", "keyboards", "webcams"] },
  { id: "samsung", name: "Samsung Shop", slug: "samsung", category: "tech", description: "Official Samsung store for phones, TVs, home appliances, and Galaxy ecosystem devices.", priceRange: "$30 – $5,000+", affiliate: "https://www.samsung.com/us/?utm_source=mysteryshop", tags: ["phones", "tvs", "appliances"] },
  { id: "dell", name: "Dell", slug: "dell", category: "tech", description: "Laptops, desktops, monitors, and servers direct from one of the world's top PC manufacturers.", priceRange: "$200 – $5,000+", affiliate: "https://www.dell.com/?utm_source=mysteryshop", tags: ["laptops", "desktops", "monitors"] },
  { id: "lenovo", name: "Lenovo", slug: "lenovo", category: "tech", description: "ThinkPads, IdeaPads, gaming laptops, and accessories from the world's largest PC maker.", priceRange: "$250 – $4,000+", affiliate: "https://www.lenovo.com/?utm_source=mysteryshop", tags: ["laptops", "tablets", "desktops"] },
  { id: "asus-store", name: "ASUS Store", slug: "asus-store", category: "tech", description: "Innovative laptops, motherboards, gaming monitors, and ROG peripherals from a top-tier brand.", priceRange: "$30 – $4,000+", affiliate: "https://www.asus.com/us/?utm_source=mysteryshop", tags: ["laptops", "gaming", "components"] },
  { id: "bestbuy", name: "Best Buy", slug: "bestbuy", category: "tech", description: "The largest US electronics retailer with everything from TVs to appliances to smart home devices.", priceRange: "$10 – $10,000+", affiliate: "https://www.bestbuy.com/?utm_source=mysteryshop", tags: ["electronics", "appliances", "tvs"] },
  { id: "dji", name: "DJI", slug: "dji", category: "tech", description: "World-class drones, gimbals, and camera stabilizers for aerial photography and videography.", priceRange: "$100 – $10,000+", affiliate: "https://www.dji.com/?utm_source=mysteryshop", tags: ["drones", "cameras", "photography"] },
  { id: "sonos", name: "Sonos", slug: "sonos", category: "tech", description: "Premium wireless smart speakers and home audio systems for audiophiles and music lovers.", priceRange: "$100 – $900", affiliate: "https://www.sonos.com/?utm_source=mysteryshop", tags: ["speakers", "audio", "smart home"] },

  // OUTDOOR
  { id: "rei", name: "REI", slug: "rei", category: "outdoor", description: "America's premier outdoor co-op selling hiking, camping, climbing, and cycling gear for every adventure.", priceRange: "$15 – $1,500+", affiliate: "https://www.rei.com/?utm_source=mysteryshop", tags: ["hiking", "camping", "cycling"] },
  { id: "backcountry", name: "Backcountry", slug: "backcountry", category: "outdoor", description: "Premium outdoor gear for skiing, hiking, climbing, and backcountry adventures from top brands.", priceRange: "$20 – $2,000+", affiliate: "https://www.backcountry.com/?utm_source=mysteryshop", tags: ["skiing", "hiking", "climbing"] },
  { id: "patagonia", name: "Patagonia", slug: "patagonia", category: "outdoor", description: "Sustainable outdoor clothing and gear company known for environmental activism and durable products.", priceRange: "$30 – $600", affiliate: "https://www.patagonia.com/?utm_source=mysteryshop", tags: ["clothing", "sustainability", "hiking"] },
  { id: "north-face", name: "The North Face", slug: "north-face", category: "outdoor", description: "Iconic outdoor brand offering jackets, backpacks, and gear for hiking, climbing, and cold weather.", priceRange: "$25 – $700", affiliate: "https://www.thenorthface.com/?utm_source=mysteryshop", tags: ["jackets", "backpacks", "hiking"] },
  { id: "cabelas", name: "Cabela's", slug: "cabelas", category: "outdoor", description: "World's foremost outfitter for hunting, fishing, and camping gear and clothing.", priceRange: "$10 – $2,000+", affiliate: "https://www.cabelas.com/?utm_source=mysteryshop", tags: ["hunting", "fishing", "camping"] },
  { id: "bass-pro", name: "Bass Pro Shops", slug: "bass-pro", category: "outdoor", description: "The ultimate destination for outdoor enthusiasts — fishing, boating, hunting, and camping.", priceRange: "$10 – $5,000+", affiliate: "https://www.basspro.com/?utm_source=mysteryshop", tags: ["fishing", "boating", "hunting"] },
  { id: "columbia", name: "Columbia Sportswear", slug: "columbia", category: "outdoor", description: "Affordable and reliable outdoor apparel and footwear for hiking, skiing, and everyday adventures.", priceRange: "$20 – $400", affiliate: "https://www.columbia.com/?utm_source=mysteryshop", tags: ["jackets", "boots", "hiking"] },
  { id: "evo", name: "evo", slug: "evo", category: "outdoor", description: "Ski, snowboard, surf, and skate gear from top brands at competitive prices.", priceRange: "$30 – $1,500+", affiliate: "https://www.evo.com/?utm_source=mysteryshop", tags: ["ski", "snowboard", "surf"] },
  { id: "moosejaw", name: "Moosejaw", slug: "moosejaw", category: "outdoor", description: "Fun outdoor gear retailer with a great selection of hiking, climbing, and camping equipment.", priceRange: "$15 – $800", affiliate: "https://www.moosejaw.com/?utm_source=mysteryshop", tags: ["hiking", "camping", "climbing"] },
  { id: "campsaver", name: "CampSaver", slug: "campsaver", category: "outdoor", description: "Discount outdoor gear retailer with deep savings on camping, backpacking, and hiking equipment.", priceRange: "$10 – $1,000+", affiliate: "https://www.campsaver.com/?utm_source=mysteryshop", tags: ["camping", "backpacking", "hiking"] },
  { id: "arcteryx", name: "Arc'teryx", slug: "arcteryx", category: "outdoor", description: "Ultra-premium outdoor performance clothing and gear built for serious alpine and outdoor pursuits.", priceRange: "$60 – $1,200+", affiliate: "https://arcteryx.com/?utm_source=mysteryshop", tags: ["jackets", "climbing", "skiing"] },
  { id: "osprey", name: "Osprey Packs", slug: "osprey", category: "outdoor", description: "Award-winning backpacks, daypacks, and travel packs built for hiking, travel, and everyday use.", priceRange: "$40 – $400", affiliate: "https://www.osprey.com/?utm_source=mysteryshop", tags: ["backpacks", "hiking", "travel"] },
  { id: "salomon", name: "Salomon", slug: "salomon", category: "outdoor", description: "High-performance trail running shoes, ski boots, and outdoor apparel for active adventurers.", priceRange: "$50 – $900", affiliate: "https://www.salomon.com/en-us/?utm_source=mysteryshop", tags: ["trail running", "skiing", "footwear"] },

  // GIFTS
  { id: "uncommon-goods", name: "UncommonGoods", slug: "uncommon-goods", category: "gifts", description: "Unique and creative gifts made by independent artists and makers. Perfect for the person who has everything.", priceRange: "$10 – $300", affiliate: "https://www.uncommongoods.com/?utm_source=mysteryshop", tags: ["unique gifts", "handmade", "artisan"] },
  { id: "things-remembered", name: "Things Remembered", slug: "things-remembered", category: "gifts", description: "Personalized gifts and keepsakes for every occasion — engravable, embroiderable, and customizable.", priceRange: "$15 – $250", affiliate: "https://www.thingsremembered.com/?utm_source=mysteryshop", tags: ["personalized", "engraving", "keepsakes"] },
  { id: "artifact-uprising", name: "Artifact Uprising", slug: "artifact-uprising", category: "gifts", description: "Premium photo books, prints, and albums that turn your memories into beautiful physical keepsakes.", priceRange: "$20 – $200", affiliate: "https://www.artifactuprising.com/?utm_source=mysteryshop", tags: ["photo books", "prints", "memories"] },
  { id: "1-800-flowers", name: "1-800-Flowers", slug: "1-800-flowers", category: "gifts", description: "Fresh flowers, plants, gourmet food, and gift baskets delivered nationwide for any occasion.", priceRange: "$25 – $200", affiliate: "https://www.1800flowers.com/?utm_source=mysteryshop", tags: ["flowers", "plants", "baskets"] },
  { id: "etsy", name: "Etsy", slug: "etsy", category: "gifts", description: "The global marketplace for unique and creative goods made by independent sellers worldwide.", priceRange: "$5 – $500+", affiliate: "https://www.etsy.com/?utm_source=mysteryshop", tags: ["handmade", "vintage", "artisan"] },
  { id: "harry-and-david", name: "Harry & David", slug: "harry-and-david", category: "gifts", description: "Premium gourmet food gifts, fruit baskets, and chocolates for holidays and special occasions.", priceRange: "$20 – $200", affiliate: "https://www.harryanddavid.com/?utm_source=mysteryshop", tags: ["gourmet", "food gifts", "baskets"] },
  { id: "zola", name: "Zola", slug: "zola", category: "gifts", description: "Modern wedding registry and gift shop with curated selections for newlyweds and home builders.", priceRange: "$20 – $1,000+", affiliate: "https://www.zola.com/?utm_source=mysteryshop", tags: ["wedding", "registry", "home"] },
  { id: "notonthehighstreet", name: "Not On The High Street", slug: "notonthehighstreet", category: "gifts", description: "Curated marketplace of unique, thoughtful gifts from small creative businesses in the UK and beyond.", priceRange: "$10 – $500", affiliate: "https://www.notonthehighstreet.com/?utm_source=mysteryshop", tags: ["unique", "creative", "handmade"] },
  { id: "personalization-mall", name: "Personalization Mall", slug: "personalization-mall", category: "gifts", description: "Thousands of personalized gifts for every occasion — monogrammed, engraved, and custom-printed.", priceRange: "$10 – $200", affiliate: "https://www.personalizationmall.com/?utm_source=mysteryshop", tags: ["personalized", "monogram", "custom"] },
  { id: "goldengifts", name: "Goldbelly", slug: "goldbelly", category: "gifts", description: "Ship iconic foods from America's best restaurants and bakeries — the ultimate foodie gift.", priceRange: "$30 – $200", affiliate: "https://www.goldbelly.com/?utm_source=mysteryshop", tags: ["food", "restaurants", "shipping"] },
  { id: "omaha-steaks", name: "Omaha Steaks", slug: "omaha-steaks", category: "gifts", description: "Premium steaks, seafood, sides, and desserts delivered — a classic gift for meat lovers.", priceRange: "$30 – $300", affiliate: "https://www.omahasteaks.com/?utm_source=mysteryshop", tags: ["steaks", "food", "grilling"] },

  // CLOTHING
  { id: "everlane", name: "Everlane", slug: "everlane", category: "clothing", description: "Minimalist, ethically-made clothing with radical transparency about factories and pricing.", priceRange: "$18 – $200", affiliate: "https://www.everlane.com/?utm_source=mysteryshop", tags: ["minimalist", "ethical", "basics"] },
  { id: "uniqlo", name: "UNIQLO", slug: "uniqlo", category: "clothing", description: "Japanese casual wear known for LifeWear — simple, high-quality clothing for everyday life.", priceRange: "$10 – $150", affiliate: "https://www.uniqlo.com/us/?utm_source=mysteryshop", tags: ["basics", "japanese", "casual"] },
  { id: "madewell", name: "Madewell", slug: "madewell", category: "clothing", description: "Effortlessly cool denim, clothing, and accessories with a timeless, lived-in aesthetic.", priceRange: "$25 – $200", affiliate: "https://www.madewell.com/?utm_source=mysteryshop", tags: ["denim", "casual", "american"] },
  { id: "allbirds", name: "Allbirds", slug: "allbirds", category: "clothing", description: "Sustainable shoes and apparel made from natural materials like merino wool and eucalyptus.", priceRange: "$50 – $160", affiliate: "https://www.allbirds.com/?utm_source=mysteryshop", tags: ["shoes", "sustainable", "wool"] },
  { id: "bonobos", name: "Bonobos", slug: "bonobos", category: "clothing", description: "Men's clothing brand famous for the best-fitting pants and smart casual styles.", priceRange: "$30 – $250", affiliate: "https://bonobos.com/?utm_source=mysteryshop", tags: ["mens", "pants", "smart casual"] },
  { id: "reformation", name: "Reformation", slug: "reformation", category: "clothing", description: "Sustainable women's fashion that is as stylish as it is eco-friendly.", priceRange: "$40 – $400", affiliate: "https://www.thereformation.com/?utm_source=mysteryshop", tags: ["womens", "sustainable", "fashion"] },
  { id: "lululemon", name: "lululemon", slug: "lululemon", category: "clothing", description: "Premium athletic apparel for yoga, running, training, and everyday life.", priceRange: "$30 – $250", affiliate: "https://www.lululemon.com/?utm_source=mysteryshop", tags: ["athletic", "yoga", "activewear"] },
  { id: "vuori", name: "Vuori", slug: "vuori", category: "clothing", description: "California-inspired performance apparel designed for versatility between workouts and everyday wear.", priceRange: "$40 – $150", affiliate: "https://www.vuoriclothing.com/?utm_source=mysteryshop", tags: ["activewear", "california", "performance"] },
  { id: "outerknown", name: "Outerknown", slug: "outerknown", category: "clothing", description: "Sustainable surf-inspired clothing co-founded by Kelly Slater, made from recycled materials.", priceRange: "$35 – $300", affiliate: "https://www.outerknown.com/?utm_source=mysteryshop", tags: ["sustainable", "surf", "casual"] },
  { id: "banana-republic", name: "Banana Republic", slug: "banana-republic", category: "clothing", description: "Sophisticated workwear and casual classics with a modern, polished aesthetic.", priceRange: "$25 – $300", affiliate: "https://bananarepublic.gap.com/?utm_source=mysteryshop", tags: ["workwear", "classic", "sophisticated"] },
  { id: "ralph-lauren", name: "Ralph Lauren", slug: "ralph-lauren", category: "clothing", description: "Iconic American fashion brand with timeless polo shirts, chinos, and luxury sportswear.", priceRange: "$30 – $500+", affiliate: "https://www.ralphlauren.com/?utm_source=mysteryshop", tags: ["american", "classic", "polo"] },
  { id: "jcrew", name: "J.Crew", slug: "jcrew", category: "clothing", description: "Classic, preppy American style with a fresh twist — great for work and weekend wardrobe building.", priceRange: "$20 – $300", affiliate: "https://www.jcrew.com/?utm_source=mysteryshop", tags: ["preppy", "american", "classic"] },
  { id: "ae", name: "American Eagle", slug: "ae", category: "clothing", description: "Casual clothing and the best-fitting jeans for young adults — stylish, comfortable, and affordable.", priceRange: "$15 – $120", affiliate: "https://www.ae.com/?utm_source=mysteryshop", tags: ["casual", "denim", "youth"] },
  { id: "asos", name: "ASOS", slug: "asos", category: "clothing", description: "Massive online fashion retailer with thousands of brands and styles for men and women.", priceRange: "$10 – $300", affiliate: "https://www.asos.com/?utm_source=mysteryshop", tags: ["fashion", "trendy", "variety"] },

  // PETS
  { id: "chewy", name: "Chewy", slug: "chewy", category: "pets", description: "America's #1 pet store for food, treats, toys, and supplies — delivered to your door with amazing customer service.", priceRange: "$5 – $300", affiliate: "https://www.chewy.com/?utm_source=mysteryshop", tags: ["pet food", "dog", "cat"] },
  { id: "petco", name: "Petco", slug: "petco", category: "pets", description: "Full-service pet retailer offering food, grooming, training, and veterinary services.", priceRange: "$5 – $500", affiliate: "https://www.petco.com/?utm_source=mysteryshop", tags: ["pet food", "grooming", "supplies"] },
  { id: "petsmart", name: "PetSmart", slug: "petsmart", category: "pets", description: "North America's largest specialty pet retailer with food, accessories, grooming, and training.", priceRange: "$5 – $400", affiliate: "https://www.petsmart.com/?utm_source=mysteryshop", tags: ["pet food", "grooming", "training"] },
  { id: "barkbox", name: "BarkBox", slug: "barkbox", category: "pets", description: "Monthly subscription boxes packed with themed toys and treats for dogs — pure puppy joy.", priceRange: "$23 – $35/month", affiliate: "https://www.barkbox.com/?utm_source=mysteryshop", tags: ["subscription", "dog toys", "treats"] },
  { id: "pet-plate", name: "Pet Plate", slug: "pet-plate", category: "pets", description: "Vet-approved fresh cooked dog food delivered weekly. Real ingredients, real nutrition.", priceRange: "$35 – $90/week", affiliate: "https://www.petplate.com/?utm_source=mysteryshop", tags: ["dog food", "fresh", "healthy"] },
  { id: "wild-one", name: "Wild One", slug: "wild-one", category: "pets", description: "Modern, design-forward pet accessories and toys that look as good in your home as they do on your pet.", priceRange: "$15 – $80", affiliate: "https://wildone.com/?utm_source=mysteryshop", tags: ["dog accessories", "design", "modern"] },
  { id: "rover", name: "Rover Store", slug: "rover", category: "pets", description: "Pet supplies, gear, and accessories curated by the team behind America's most trusted pet services platform.", priceRange: "$10 – $200", affiliate: "https://store.rover.com/?utm_source=mysteryshop", tags: ["dog", "cat", "accessories"] },
  { id: "ollies-place", name: "Ollie's Pet Food", slug: "ollies-place", category: "pets", description: "Fresh, human-grade dog food made from real whole food ingredients and customized for your pup.", priceRange: "$35 – $100/week", affiliate: "https://www.myollie.com/?utm_source=mysteryshop", tags: ["dog food", "fresh", "customized"] },
  { id: "ruffwear", name: "Ruffwear", slug: "ruffwear", category: "pets", description: "Performance gear for adventure dogs — harnesses, boots, jackets, and packs for the trail.", priceRange: "$20 – $150", affiliate: "https://ruffwear.com/?utm_source=mysteryshop", tags: ["dog gear", "hiking", "adventure"] },
  { id: "petflow", name: "PetFlow", slug: "petflow", category: "pets", description: "Auto-ship pet food and supplies with great prices and convenient subscription scheduling.", priceRange: "$10 – $200", affiliate: "https://www.petflow.com/?utm_source=mysteryshop", tags: ["pet food", "auto-ship", "subscription"] },

  // GAMING
  { id: "gamestop", name: "GameStop", slug: "gamestop", category: "gaming", description: "The iconic video game retailer for new and used games, consoles, controllers, and accessories.", priceRange: "$5 – $600", affiliate: "https://www.gamestop.com/?utm_source=mysteryshop", tags: ["games", "consoles", "used games"] },
  { id: "funko", name: "Funko", slug: "funko", category: "gaming", description: "Home of Pop! vinyl collectibles featuring thousands of pop culture characters from games, movies, and TV.", priceRange: "$10 – $100", affiliate: "https://www.funko.com/?utm_source=mysteryshop", tags: ["collectibles", "pop vinyl", "figures"] },
  { id: "humble-bundle", name: "Humble Bundle", slug: "humble-bundle", category: "gaming", description: "Pay what you want for bundles of PC games, books, and software while supporting charity.", priceRange: "$1 – $30", affiliate: "https://www.humblebundle.com/?utm_source=mysteryshop", tags: ["pc games", "bundles", "charity"] },
  { id: "green-man-gaming", name: "Green Man Gaming", slug: "green-man-gaming", category: "gaming", description: "Licensed PC game retailer offering huge discounts on AAA titles and indie games with reward points.", priceRange: "$1 – $70", affiliate: "https://www.greenmangaming.com/?utm_source=mysteryshop", tags: ["pc games", "discounts", "digital"] },
  { id: "indiebox", name: "Limited Run Games", slug: "indiebox", category: "gaming", description: "Physical editions of digital-only games — collector's sets and limited runs for hardcore gamers.", priceRange: "$20 – $200", affiliate: "https://limitedrungames.com/?utm_source=mysteryshop", tags: ["physical games", "collectors", "limited"] },
  { id: "controller-chaos", name: "Controller Chaos", slug: "controller-chaos", category: "gaming", description: "Fully custom-designed PlayStation and Xbox controllers built to your exact color and button specs.", priceRange: "$70 – $200", affiliate: "https://controllerchaos.com/?utm_source=mysteryshop", tags: ["controllers", "custom", "ps5 xbox"] },
  { id: "hero-stuff", name: "ThinkGeek", slug: "hero-stuff", category: "gaming", description: "Geek culture merchandise, gaming collectibles, gadgets, and apparel for the ultimate nerd.", priceRange: "$10 – $200", affiliate: "https://www.thinkgeek.com/?utm_source=mysteryshop", tags: ["geek", "collectibles", "merchandise"] },
  { id: "box-lunch", name: "BoxLunch", slug: "box-lunch", category: "gaming", description: "Fandom-inspired apparel, accessories, and gifts from your favorite movies, games, and TV shows.", priceRange: "$10 – $150", affiliate: "https://www.boxlunch.com/?utm_source=mysteryshop", tags: ["fandom", "apparel", "pop culture"] },
  { id: "hot-topic", name: "Hot Topic", slug: "hot-topic", category: "gaming", description: "Pop culture merchandise, band tees, and fan gear for music, gaming, and entertainment lovers.", priceRange: "$10 – $100", affiliate: "https://www.hottopic.com/?utm_source=mysteryshop", tags: ["pop culture", "band merch", "fan gear"] },
  { id: "pcgamingrace", name: "PCMR Store", slug: "pcgamingrace", category: "gaming", description: "Gaming PC peripherals, custom keycaps, mousepads, and accessories for the master race.", priceRange: "$10 – $300", affiliate: "https://www.pcgamingrace.com/?utm_source=mysteryshop", tags: ["mechanical keyboards", "mice", "pc gaming"] },

  // HOME
  { id: "article", name: "Article", slug: "article", category: "home", description: "Direct-to-consumer modern furniture with Scandinavian-inspired design at fair prices.", priceRange: "$100 – $3,000", affiliate: "https://www.article.com/?utm_source=mysteryshop", tags: ["furniture", "modern", "scandinavian"] },
  { id: "wayfair", name: "Wayfair", slug: "wayfair", category: "home", description: "The largest online home goods store with millions of products for every room and style.", priceRange: "$10 – $5,000+", affiliate: "https://www.wayfair.com/?utm_source=mysteryshop", tags: ["furniture", "decor", "home goods"] },
  { id: "west-elm", name: "West Elm", slug: "west-elm", category: "home", description: "Modern home furnishings and decor with an emphasis on sustainability and fair trade practices.", priceRange: "$20 – $2,500", affiliate: "https://www.westelm.com/?utm_source=mysteryshop", tags: ["modern", "sustainable", "furniture"] },
  { id: "pottery-barn", name: "Pottery Barn", slug: "pottery-barn", category: "home", description: "Classic American home furnishings and decor with timeless, quality craftsmanship.", priceRange: "$30 – $5,000+", affiliate: "https://www.potterybarn.com/?utm_source=mysteryshop", tags: ["classic", "furniture", "decor"] },
  { id: "crate-barrel", name: "Crate & Barrel", slug: "crate-barrel", category: "home", description: "Contemporary furniture, housewares, and kitchenware with a focus on quality and modern design.", priceRange: "$20 – $4,000+", affiliate: "https://www.crateandbarrel.com/?utm_source=mysteryshop", tags: ["furniture", "kitchenware", "modern"] },
  { id: "cb2", name: "CB2", slug: "cb2", category: "home", description: "Modern, edgy furniture and decor for urban living — Crate & Barrel's cool younger sibling.", priceRange: "$20 – $3,000+", affiliate: "https://www.cb2.com/?utm_source=mysteryshop", tags: ["modern", "urban", "furniture"] },
  { id: "ikea", name: "IKEA", slug: "ikea", category: "home", description: "Swedish flat-pack furniture and home accessories that make smart design available to everyone.", priceRange: "$5 – $2,000", affiliate: "https://www.ikea.com/us/?utm_source=mysteryshop", tags: ["furniture", "swedish", "affordable"] },
  { id: "serena-lily", name: "Serena & Lily", slug: "serena-lily", category: "home", description: "Coastal-inspired home decor and furniture with a relaxed California aesthetic.", priceRange: "$30 – $4,000+", affiliate: "https://www.serenaandlily.com/?utm_source=mysteryshop", tags: ["coastal", "california", "decor"] },
  { id: "world-market", name: "World Market", slug: "world-market", category: "home", description: "Global-inspired home decor, furniture, food, and wine from around the world.", priceRange: "$5 – $1,000", affiliate: "https://www.worldmarket.com/?utm_source=mysteryshop", tags: ["global", "decor", "eclectic"] },
  { id: "overstock", name: "Overstock", slug: "overstock", category: "home", description: "Discounted furniture, bedding, and home decor with deep savings on brand-name products.", priceRange: "$10 – $3,000+", affiliate: "https://www.overstock.com/?utm_source=mysteryshop", tags: ["discount", "furniture", "bedding"] },
  { id: "sur-la-table", name: "Sur La Table", slug: "sur-la-table", category: "home", description: "Premium cookware, bakeware, and kitchen gadgets for the home chef and culinary enthusiast.", priceRange: "$10 – $800", affiliate: "https://www.surlatable.com/?utm_source=mysteryshop", tags: ["cookware", "kitchen", "baking"] },
  { id: "williams-sonoma", name: "Williams Sonoma", slug: "williams-sonoma", category: "home", description: "Luxury cookware, kitchen appliances, and gourmet food from the world's premier cooking brand.", priceRange: "$20 – $3,000+", affiliate: "https://www.williams-sonoma.com/?utm_source=mysteryshop", tags: ["cookware", "kitchen", "luxury"] },

  // ADDITIONAL TECH
  { id: "bhphotovideo", name: "BH Professional Video", slug: "bhprofvideo", category: "tech", description: "Broadcast video cameras, lenses, lighting rigs, and studio equipment for professional productions.", priceRange: "$50 – $20,000+", affiliate: "https://www.bhphotovideo.com/c/browse/Professional-Video/ci/15549?utm_source=mysteryshop", tags: ["video", "broadcast", "professional"] },
  { id: "apple", name: "Apple", slug: "apple", category: "tech", description: "iPhones, MacBooks, iPads, AirPods, and the entire Apple ecosystem of premium hardware and software.", priceRange: "$30 – $7,000+", affiliate: "https://www.apple.com/?utm_source=mysteryshop", tags: ["iphone", "mac", "ipad"] },
  { id: "google-store", name: "Google Store", slug: "google-store", category: "tech", description: "Pixel phones, Nest smart home devices, Chromebooks, and other Google hardware products.", priceRange: "$30 – $2,000", affiliate: "https://store.google.com/?utm_source=mysteryshop", tags: ["pixel", "nest", "chromebook"] },
  { id: "microsoft", name: "Microsoft Store", slug: "microsoft", category: "tech", description: "Surface laptops, Xbox consoles, Windows software, and Microsoft 365 subscriptions.", priceRange: "$30 – $4,000+", affiliate: "https://www.microsoft.com/en-us/store?utm_source=mysteryshop", tags: ["surface", "xbox", "windows"] },
  { id: "jabra", name: "Jabra", slug: "jabra", category: "tech", description: "Premium wireless earbuds and professional headsets for calls, music, and hybrid work.", priceRange: "$30 – $350", affiliate: "https://www.jabra.com/en-us?utm_source=mysteryshop", tags: ["earbuds", "headsets", "audio"] },
  { id: "bose", name: "Bose", slug: "bose", category: "tech", description: "Industry-leading noise-canceling headphones and premium speakers trusted by audiophiles everywhere.", priceRange: "$50 – $500", affiliate: "https://www.bose.com/?utm_source=mysteryshop", tags: ["headphones", "speakers", "noise-canceling"] },
  { id: "sennheiser", name: "Sennheiser", slug: "sennheiser", category: "tech", description: "Professional-grade audio equipment, studio headphones, and microphones used by recording engineers.", priceRange: "$30 – $2,000+", affiliate: "https://www.sennheiser.com/en-us/?utm_source=mysteryshop", tags: ["headphones", "microphones", "pro audio"] },
  { id: "elgato", name: "Elgato", slug: "elgato", category: "tech", description: "Stream decks, capture cards, and streaming accessories that level up any content creator's setup.", priceRange: "$30 – $300", affiliate: "https://www.elgato.com/?utm_source=mysteryshop", tags: ["streaming", "capture cards", "creators"] },

  // ADDITIONAL OUTDOOR
  { id: "yeti", name: "YETI", slug: "yeti", category: "outdoor", description: "Legendary coolers, drinkware, and outdoor gear built to handle the toughest conditions in nature.", priceRange: "$30 – $500", affiliate: "https://www.yeti.com/?utm_source=mysteryshop", tags: ["coolers", "drinkware", "camping"] },
  { id: "hydroflask", name: "Hydro Flask", slug: "hydroflask", category: "outdoor", description: "Insulated water bottles, food containers, and drinkware designed for outdoor adventure and daily life.", priceRange: "$20 – $80", affiliate: "https://www.hydroflask.com/?utm_source=mysteryshop", tags: ["water bottles", "insulated", "outdoor"] },
  { id: "klean-kanteen", name: "Klean Kanteen", slug: "klean-kanteen", category: "outdoor", description: "Sustainable insulated stainless steel bottles, mugs, and food containers for eco-conscious adventurers.", priceRange: "$15 – $60", affiliate: "https://www.kleankanteen.com/?utm_source=mysteryshop", tags: ["water bottles", "sustainable", "stainless"] },
  { id: "nemo-equipment", name: "NEMO Equipment", slug: "nemo-equipment", category: "outdoor", description: "Innovative tents, sleeping bags, and sleeping pads engineered for weight-conscious backpackers.", priceRange: "$40 – $1,000+", affiliate: "https://www.nemoequipment.com/?utm_source=mysteryshop", tags: ["tents", "sleeping bags", "backpacking"] },
  { id: "black-diamond", name: "Black Diamond", slug: "black-diamond", category: "outdoor", description: "Climbing and skiing equipment from the original innovators of modern rock climbing gear.", priceRange: "$20 – $1,000+", affiliate: "https://www.blackdiamondequipment.com/?utm_source=mysteryshop", tags: ["climbing", "skiing", "headlamps"] },
  { id: "msr", name: "MSR", slug: "msr", category: "outdoor", description: "Ultralight camping stoves, cookware, tents, and water filters trusted by serious backpackers worldwide.", priceRange: "$25 – $700", affiliate: "https://www.msrgear.com/?utm_source=mysteryshop", tags: ["camping stoves", "tents", "water filters"] },
  { id: "prana", name: "prAna", slug: "prana", category: "outdoor", description: "Sustainable yoga and climbing apparel made from organic and recycled materials for active lifestyles.", priceRange: "$25 – $200", affiliate: "https://www.prana.com/?utm_source=mysteryshop", tags: ["yoga", "climbing", "sustainable clothing"] },

  // ADDITIONAL GIFTS
  { id: "edible-arrangements", name: "Edible Arrangements", slug: "edible-arrangements", category: "gifts", description: "Fresh fruit bouquets, chocolate dipped treats, and sweet gifts delivered for any occasion.", priceRange: "$25 – $150", affiliate: "https://www.ediblearrangements.com/?utm_source=mysteryshop", tags: ["fruit", "chocolate", "fresh gifts"] },
  { id: "shutterfly", name: "Shutterfly", slug: "shutterfly", category: "gifts", description: "Photo gifts, personalized cards, books, and home decor created from your own photos.", priceRange: "$5 – $100", affiliate: "https://www.shutterfly.com/?utm_source=mysteryshop", tags: ["photo gifts", "personalized", "cards"] },
  { id: "brookstone", name: "Brookstone", slug: "brookstone", category: "gifts", description: "Unique gadgets, massagers, and innovative gifts for people who have everything.", priceRange: "$20 – $500", affiliate: "https://www.brookstone.com/?utm_source=mysteryshop", tags: ["gadgets", "massagers", "unique"] },
  { id: "wine-com", name: "Wine.com", slug: "wine-com", category: "gifts", description: "The largest online wine retailer — send thoughtful bottles, curated packs, and wine gift sets.", priceRange: "$10 – $500", affiliate: "https://www.wine.com/?utm_source=mysteryshop", tags: ["wine", "gifts", "delivery"] },
  { id: "godiva", name: "Godiva", slug: "godiva", category: "gifts", description: "Iconic Belgian chocolate truffles, gift boxes, and seasonal confections for every celebration.", priceRange: "$10 – $150", affiliate: "https://www.godiva.com/?utm_source=mysteryshop", tags: ["chocolate", "truffles", "luxury"] },
  { id: "terrain", name: "Terrain", slug: "terrain", category: "gifts", description: "Unique home and garden gifts with a botanical, nature-inspired aesthetic for creative souls.", priceRange: "$15 – $300", affiliate: "https://www.shopterrain.com/?utm_source=mysteryshop", tags: ["garden", "botanical", "home gifts"] },

  // ADDITIONAL CLOTHING
  { id: "pact", name: "PACT", slug: "pact", category: "clothing", description: "Organic cotton clothing and underwear made in Fair Trade-certified factories at affordable prices.", priceRange: "$12 – $100", affiliate: "https://wearpact.com/?utm_source=mysteryshop", tags: ["organic", "underwear", "sustainable"] },
  { id: "proozy", name: "Proozy", slug: "proozy", category: "clothing", description: "Discount name-brand athletic and casual clothing from top brands at deeply discounted prices.", priceRange: "$10 – $100", affiliate: "https://proozy.com/?utm_source=mysteryshop", tags: ["discount", "athletic", "brands"] },
  { id: "threadless", name: "Threadless", slug: "threadless", category: "clothing", description: "Artist-designed T-shirts, hoodies, and accessories from an independent art community.", priceRange: "$15 – $60", affiliate: "https://www.threadless.com/?utm_source=mysteryshop", tags: ["art", "t-shirts", "independent artists"] },
  { id: "redbubble", name: "Redbubble", slug: "redbubble", category: "clothing", description: "Independent artist marketplace with unique clothing, stickers, posters, and accessories.", priceRange: "$5 – $80", affiliate: "https://www.redbubble.com/?utm_source=mysteryshop", tags: ["art", "independent", "custom"] },
  { id: "taylor-stitch", name: "Taylor Stitch", slug: "taylor-stitch", category: "clothing", description: "Durable, well-designed men's clothing built to last — work shirts, chinos, and outerwear.", priceRange: "$50 – $300", affiliate: "https://www.taylorstitch.com/?utm_source=mysteryshop", tags: ["mens", "durable", "workwear"] },
  { id: "ministry-of-supply", name: "Ministry of Supply", slug: "ministry-of-supply", category: "clothing", description: "Performance office wear combining engineering and style — wrinkle-free, machine washable dress clothes.", priceRange: "$50 – $250", affiliate: "https://www.ministryofsupply.com/?utm_source=mysteryshop", tags: ["performance", "office wear", "tech fabric"] },
  { id: "huckberry", name: "Huckberry", slug: "huckberry", category: "clothing", description: "Curated outdoor-inspired lifestyle clothing and gear for modern adventurers.", priceRange: "$20 – $400", affiliate: "https://huckberry.com/?utm_source=mysteryshop", tags: ["outdoor", "lifestyle", "mens"] },

  // ADDITIONAL PETS
  { id: "instinct-pet", name: "Nature's Variety Instinct", slug: "instinct-pet", category: "pets", description: "Raw and natural pet food using real animal protein for dogs and cats who deserve the best nutrition.", priceRange: "$15 – $80", affiliate: "https://www.instinct.com/?utm_source=mysteryshop", tags: ["raw food", "natural", "dog cat"] },
  { id: "zooplus", name: "Zooplus", slug: "zooplus", category: "pets", description: "Europe's largest online pet shop with a vast selection of food, toys, and accessories at low prices.", priceRange: "$5 – $300", affiliate: "https://www.zooplus.com/?utm_source=mysteryshop", tags: ["pet food", "toys", "accessories"] },
  { id: "petcube", name: "Petcube", slug: "petcube", category: "pets", description: "Smart pet cameras with treat tossers and two-way audio so you can monitor and play with pets remotely.", priceRange: "$50 – $200", affiliate: "https://petcube.com/?utm_source=mysteryshop", tags: ["pet camera", "smart", "treats"] },
  { id: "pawstruck", name: "Pawstruck", slug: "pawstruck", category: "pets", description: "All-natural dog chews, treats, and bones sourced without artificial preservatives or additives.", priceRange: "$8 – $60", affiliate: "https://www.pawstruck.com/?utm_source=mysteryshop", tags: ["dog treats", "natural", "chews"] },
  { id: "kurgo", name: "Kurgo", slug: "kurgo", category: "pets", description: "Travel and adventure gear for dogs — harnesses, car seats, leashes, and outdoor equipment.", priceRange: "$15 – $150", affiliate: "https://www.kurgo.com/?utm_source=mysteryshop", tags: ["dog travel", "harnesses", "car"] },

  // ADDITIONAL GAMING
  { id: "bandai-namco", name: "Bandai Namco Store", slug: "bandai-namco", category: "gaming", description: "Official merch, figures, and collectibles from iconic game franchises like Tekken, Pac-Man, and Dark Souls.", priceRange: "$10 – $200", affiliate: "https://store.bandainamcoent.com/?utm_source=mysteryshop", tags: ["merch", "figures", "collectibles"] },
  { id: "kinguin", name: "Kinguin", slug: "kinguin", category: "gaming", description: "Marketplace for buying and selling digital game keys across all major platforms at competitive prices.", priceRange: "$1 – $60", affiliate: "https://www.kinguin.net/?utm_source=mysteryshop", tags: ["game keys", "digital", "marketplace"] },
  { id: "fanatical", name: "Fanatical", slug: "fanatical", category: "gaming", description: "PC game bundles and deals including indie titles, AAA discounts, and Steam key giveaways.", priceRange: "$1 – $60", affiliate: "https://www.fanatical.com/?utm_source=mysteryshop", tags: ["pc games", "bundles", "steam"] },
  { id: "figure-prints", name: "Sideshow Collectibles", slug: "sideshow-collectibles", category: "gaming", description: "Premium statues, figures, and collectibles from major gaming and entertainment franchises.", priceRange: "$30 – $1,000+", affiliate: "https://www.sideshowtoy.com/?utm_source=mysteryshop", tags: ["collectibles", "statues", "figures"] },
  { id: "razer-gold", name: "Razer Gold", slug: "razer-gold", category: "gaming", description: "Digital gaming currency for purchasing in-game items, passes, and currency across hundreds of games.", priceRange: "$5 – $200", affiliate: "https://gold.razer.com/?utm_source=mysteryshop", tags: ["in-game currency", "digital", "gaming"] },

  // ADDITIONAL HOME
  { id: "parachute", name: "Parachute Home", slug: "parachute", category: "home", description: "Luxuriously soft bedding, towels, and bath goods made from premium natural materials.", priceRange: "$20 – $500", affiliate: "https://www.parachutehome.com/?utm_source=mysteryshop", tags: ["bedding", "towels", "linen"] },
  { id: "saatva", name: "Saatva", slug: "saatva", category: "home", description: "Luxury innerspring mattresses delivered free with white glove service at an accessible price point.", priceRange: "$800 – $3,000+", affiliate: "https://www.saatva.com/?utm_source=mysteryshop", tags: ["mattresses", "sleep", "luxury"] },
  { id: "casper", name: "Casper", slug: "casper", category: "home", description: "Sleep brand that revolutionized the mattress industry with bed-in-a-box delivery and sleep accessories.", priceRange: "$100 – $3,000", affiliate: "https://casper.com/?utm_source=mysteryshop", tags: ["mattresses", "pillows", "sleep"] },
  { id: "purple", name: "Purple", slug: "purple", category: "home", description: "Innovative mattresses featuring GelFlex Grid technology that adapts to your body for cooler sleep.", priceRange: "$200 – $3,500", affiliate: "https://purple.com/?utm_source=mysteryshop", tags: ["mattresses", "innovative", "cooling"] },
  { id: "allform", name: "Allform", slug: "allform", category: "home", description: "Modular sofas and sectionals with pet-friendly, stain-resistant performance fabric options.", priceRange: "$500 – $3,000+", affiliate: "https://www.allform.com/?utm_source=mysteryshop", tags: ["sofas", "modular", "sectionals"] },
  { id: "plant-therapy", name: "Plant Therapy", slug: "plant-therapy", category: "home", description: "Affordable, high-quality essential oils, diffusers, and natural wellness products for the home.", priceRange: "$5 – $100", affiliate: "https://www.planttherapy.com/?utm_source=mysteryshop", tags: ["essential oils", "diffusers", "wellness"] },
  { id: "grove-collaborative", name: "Grove Collaborative", slug: "grove-collaborative", category: "home", description: "Sustainable home, cleaning, and personal care products from eco-friendly brands delivered to your door.", priceRange: "$5 – $80", affiliate: "https://www.grove.co/?utm_source=mysteryshop", tags: ["sustainable", "cleaning", "eco-friendly"] },
  { id: "the-container-store", name: "The Container Store", slug: "the-container-store", category: "home", description: "Storage and organization solutions for every space in your home — closets, kitchens, and beyond.", priceRange: "$5 – $500", affiliate: "https://www.containerstore.com/?utm_source=mysteryshop", tags: ["storage", "organization", "closets"] },
  { id: "bed-bath", name: "Bed Bath & Beyond", slug: "bed-bath", category: "home", description: "Everything you need for your home — bedding, cookware, storage, and cleaning products.", priceRange: "$5 – $500", affiliate: "https://www.bedbathandbeyond.com/?utm_source=mysteryshop", tags: ["bedding", "kitchen", "bath"] },
  { id: "restoration-hardware", name: "RH (Restoration Hardware)", slug: "restoration-hardware", category: "home", description: "Ultra-luxury home furnishings, outdoor furniture, and decor with architectural-grade quality.", priceRange: "$100 – $20,000+", affiliate: "https://rh.com/?utm_source=mysteryshop", tags: ["luxury", "furniture", "outdoor"] },

  // BONUS STORES (to reach 200+)
  { id: "chewy-pharmacy", name: "Chewy Pharmacy", slug: "chewy-pharmacy", category: "pets", description: "Licensed online pet pharmacy for prescription medications, flea & tick prevention, and heartworm.", priceRange: "$10 – $150", affiliate: "https://www.chewy.com/b/pharmacy-332?utm_source=mysteryshop", tags: ["medication", "prevention", "prescription"] },
  { id: "carbon-coco", name: "Activated Eco", slug: "activated-eco", category: "home", description: "Natural eco-friendly personal care and home products including bamboo toothbrushes and charcoal items.", priceRange: "$8 – $60", affiliate: "https://activatedeco.com/?utm_source=mysteryshop", tags: ["eco-friendly", "natural", "bamboo"] },
  { id: "nespresso", name: "Nespresso", slug: "nespresso", category: "home", description: "Premium espresso machines and coffee pods that bring café-quality drinks into your home.", priceRange: "$30 – $700", affiliate: "https://www.nespresso.com/us/?utm_source=mysteryshop", tags: ["coffee", "espresso", "pods"] },
  { id: "fellow-products", name: "Fellow", slug: "fellow", category: "home", description: "Beautiful, precision coffee brewing gear including kettles, grinders, and coffee accessories.", priceRange: "$30 – $300", affiliate: "https://fellowproducts.com/?utm_source=mysteryshop", tags: ["coffee", "brewing", "design"] },
  { id: "barebones", name: "Barebones Living", slug: "barebones-living", category: "outdoor", description: "Beautifully designed camp cooking gear, lanterns, and garden tools with a nostalgic, rustic style.", priceRange: "$20 – $300", affiliate: "https://www.barebonesliving.com/?utm_source=mysteryshop", tags: ["camping", "cooking", "lanterns"] },
  { id: "tentree", name: "tentree", slug: "tentree", category: "clothing", description: "Sustainable clothing brand that plants 10 trees for every item purchased — style that gives back.", priceRange: "$25 – $200", affiliate: "https://www.tentree.com/?utm_source=mysteryshop", tags: ["sustainable", "trees", "eco fashion"] },
  { id: "bombas", name: "Bombas", slug: "bombas", category: "clothing", description: "Incredibly comfortable socks, underwear, and t-shirts that donate one item for every purchase made.", priceRange: "$12 – $80", affiliate: "https://bombas.com/?utm_source=mysteryshop", tags: ["socks", "donation", "comfort"] },
  { id: "chubbies", name: "Chubbies", slug: "chubbies", category: "clothing", description: "Fun, retro-inspired men's shorts and swimwear built for weekends and good times at the beach.", priceRange: "$40 – $100", affiliate: "https://www.chubbiesshorts.com/?utm_source=mysteryshop", tags: ["shorts", "swimwear", "mens"] },
  { id: "shinesty", name: "Shinesty", slug: "shinesty", category: "clothing", description: "Boldly patterned underwear, holiday suits, and party clothing for people who refuse to be boring.", priceRange: "$20 – $200", affiliate: "https://www.shinesty.com/?utm_source=mysteryshop", tags: ["fun", "patterns", "party clothing"] },
  { id: "meundies", name: "MeUndies", slug: "meundies", category: "clothing", description: "Ultra-soft micro modal underwear and loungewear in playful prints delivered via subscription.", priceRange: "$16 – $36", affiliate: "https://www.meundies.com/?utm_source=mysteryshop", tags: ["underwear", "soft", "subscription"] },
  { id: "quay", name: "Quay Australia", slug: "quay", category: "clothing", description: "Trendy, affordable sunglasses and eyewear favored by influencers and fashion-forward shoppers.", priceRange: "$25 – $80", affiliate: "https://www.quayaustralia.com/?utm_source=mysteryshop", tags: ["sunglasses", "eyewear", "trendy"] },
  { id: "diff-eyewear", name: "DIFF Eyewear", slug: "diff-eyewear", category: "clothing", description: "Stylish prescription and non-prescription eyewear that donates glasses to those in need globally.", priceRange: "$25 – $100", affiliate: "https://diffeyewear.com/?utm_source=mysteryshop", tags: ["sunglasses", "eyewear", "donation"] },
  { id: "curology", name: "Curology", slug: "curology", category: "clothing", description: "Custom skincare formulas prescribed by dermatology providers and delivered to your door monthly.", priceRange: "$20 – $60/month", affiliate: "https://curology.com/?utm_source=mysteryshop", tags: ["skincare", "custom", "prescription"] },
  { id: "amazon-renewed", name: "Amazon Renewed", slug: "amazon-renewed", category: "tech", description: "Certified refurbished electronics and tech products with Amazon's guarantee — save big on premium gear.", priceRange: "$20 – $2,000", affiliate: "https://www.amazon.com/renewed?utm_source=mysteryshop", tags: ["refurbished", "certified", "electronics"] },
  { id: "back-market", name: "Back Market", slug: "back-market", category: "tech", description: "Europe's leading marketplace for refurbished tech — phones, laptops, and tablets at great prices.", priceRange: "$50 – $1,500", affiliate: "https://www.backmarket.com/?utm_source=mysteryshop", tags: ["refurbished", "phones", "laptops"] },
  { id: "swappa", name: "Swappa", slug: "swappa", category: "tech", description: "The safe peer-to-peer marketplace for buying and selling used phones, laptops, and tablets.", priceRange: "$50 – $1,200", affiliate: "https://swappa.com/?utm_source=mysteryshop", tags: ["used phones", "marketplace", "safe"] },
  { id: "audiophile-shop", name: "Audio Advice", slug: "audio-advice", category: "tech", description: "High-end audio equipment including speakers, amplifiers, turntables, and home theater systems.", priceRange: "$50 – $10,000+", affiliate: "https://www.audioadvice.com/?utm_source=mysteryshop", tags: ["hi-fi", "speakers", "amplifiers"] },
  { id: "adorama-rentals", name: "KitSplit", slug: "kitsplit", category: "tech", description: "Rent professional photo and video equipment by the day — cameras, lenses, drones, and lighting.", priceRange: "$20 – $500/day", affiliate: "https://kitsplit.com/?utm_source=mysteryshop", tags: ["rental", "cameras", "lenses"] },
  { id: "joann", name: "JOANN", slug: "joann", category: "gifts", description: "Fabric, yarn, craft supplies, and DIY materials for sewing, quilting, and creative projects.", priceRange: "$3 – $200", affiliate: "https://www.joann.com/?utm_source=mysteryshop", tags: ["crafts", "fabric", "sewing"] },
  { id: "michaels", name: "Michaels", slug: "michaels", category: "gifts", description: "America's largest arts and crafts retail chain with supplies for every creative project imaginable.", priceRange: "$2 – $300", affiliate: "https://www.michaels.com/?utm_source=mysteryshop", tags: ["crafts", "art supplies", "DIY"] },
  { id: "blick", name: "Blick Art Materials", slug: "blick", category: "gifts", description: "Comprehensive art supply store with professional paints, brushes, canvases, and student materials.", priceRange: "$3 – $500", affiliate: "https://www.dickblick.com/?utm_source=mysteryshop", tags: ["art supplies", "paints", "professional"] },
  { id: "lego", name: "LEGO", slug: "lego", category: "gifts", description: "The iconic Danish building block brand with sets for every age from city layouts to NASA rockets.", priceRange: "$10 – $800+", affiliate: "https://www.lego.com/en-us?utm_source=mysteryshop", tags: ["building blocks", "kids", "collectible sets"] },
  { id: "funko-shop", name: "Funko Shop", slug: "funko-shop", category: "gifts", description: "Exclusive and limited-edition Pop! vinyl figures, games, and apparel direct from Funko.", priceRange: "$10 – $200", affiliate: "https://shop.funko.com/?utm_source=mysteryshop", tags: ["pop vinyl", "exclusive", "collectibles"] },
  { id: "spin-master", name: "Spin Master", slug: "spin-master", category: "gifts", description: "Creative children's toys including Kinetic Sand, PAW Patrol, Hatchimals, and award-winning games.", priceRange: "$10 – $100", affiliate: "https://www.spinmaster.com/?utm_source=mysteryshop", tags: ["kids toys", "games", "creative"] },
  { id: "kikkerland", name: "Kikkerland Design", slug: "kikkerland", category: "gifts", description: "Quirky, design-forward gifts, gadgets, and home accessories that make you smile.", priceRange: "$5 – $80", affiliate: "https://www.kikkerland.com/?utm_source=mysteryshop", tags: ["quirky gifts", "design", "gadgets"] },
  { id: "fathom", name: "Gifts for Good", slug: "gifts-for-good", category: "gifts", description: "Curated gifts that give back — every purchase supports a social or environmental cause.", priceRange: "$15 – $200", affiliate: "https://www.giftsforgood.com/?utm_source=mysteryshop", tags: ["charitable", "social good", "meaningful gifts"] },
  { id: "terrain-garden", name: "Terrain Garden", slug: "terrain-garden", category: "outdoor", description: "Garden plants, tools, and outdoor lifestyle products with an earthy, design-forward aesthetic.", priceRange: "$10 – $400", affiliate: "https://www.shopterrain.com/garden?utm_source=mysteryshop", tags: ["garden", "plants", "tools"] },
  { id: "national-geographic", name: "Nat Geo Shop", slug: "nat-geo", category: "gifts", description: "Branded products, maps, books, and gifts from National Geographic supporting exploration and science.", priceRange: "$10 – $150", affiliate: "https://www.shopnatgeo.com/?utm_source=mysteryshop", tags: ["education", "maps", "books"] },
  { id: "uncommon-knowledge", name: "Uncommon Knowledge", slug: "uncommon-knowledge", category: "gifts", description: "Unusual psychology books, games, and unique gifts that challenge how you think about the world.", priceRange: "$10 – $80", affiliate: "https://www.uncommonknowledge.com/?utm_source=mysteryshop", tags: ["psychology", "books", "unusual"] },
  { id: "discovery-store", name: "Discovery Store", slug: "discovery-store", category: "gifts", description: "STEM toys, science kits, and educational products inspired by Discovery Channel for curious minds.", priceRange: "$15 – $200", affiliate: "https://www.discoverystore.com/?utm_source=mysteryshop", tags: ["STEM", "science kits", "educational"] },
  { id: "hammacher", name: "Hammacher Schlemmer", slug: "hammacher", category: "gifts", description: "The best, the only, and the unexpected — unique gadgets and remarkable items since 1848.", priceRange: "$20 – $5,000+", affiliate: "https://www.hammacher.com/?utm_source=mysteryshop", tags: ["gadgets", "unique", "innovative"] },
  { id: "sharper-image", name: "Sharper Image", slug: "sharper-image", category: "gifts", description: "Innovative electronics, massagers, air purifiers, and lifestyle gadgets for modern living.", priceRange: "$20 – $500", affiliate: "https://www.sharperimage.com/?utm_source=mysteryshop", tags: ["gadgets", "massagers", "electronics"] },
  { id: "vans", name: "Vans", slug: "vans", category: "clothing", description: "The original action sports footwear and apparel brand beloved by skaters, surfers, and creatives.", priceRange: "$25 – $150", affiliate: "https://www.vans.com/?utm_source=mysteryshop", tags: ["skate", "shoes", "casual"] },
  { id: "converse", name: "Converse", slug: "converse", category: "clothing", description: "Iconic Chuck Taylor sneakers and casual apparel that have defined cool since 1917.", priceRange: "$25 – $120", affiliate: "https://www.converse.com/?utm_source=mysteryshop", tags: ["sneakers", "classic", "casual"] },
  { id: "nike", name: "Nike", slug: "nike", category: "clothing", description: "The world's leading athletic footwear and apparel brand — just do it.", priceRange: "$25 – $400", affiliate: "https://www.nike.com/?utm_source=mysteryshop", tags: ["athletic", "shoes", "sportswear"] },
  { id: "adidas", name: "Adidas", slug: "adidas", category: "clothing", description: "Global sportswear giant with iconic sneakers, athletic apparel, and streetwear collaborations.", priceRange: "$20 – $300", affiliate: "https://www.adidas.com/us?utm_source=mysteryshop", tags: ["athletic", "sneakers", "streetwear"] },
  { id: "new-balance", name: "New Balance", slug: "new-balance", category: "clothing", description: "Made in America sneakers and athletic gear known for exceptional fit and performance.", priceRange: "$50 – $200", affiliate: "https://www.newbalance.com/?utm_source=mysteryshop", tags: ["sneakers", "running", "made in usa"] },
  { id: "on-running", name: "On Running", slug: "on-running", category: "clothing", description: "Swiss-engineered running shoes with CloudTec cushioning that feel like running on clouds.", priceRange: "$100 – $200", affiliate: "https://www.on-running.com/en-us?utm_source=mysteryshop", tags: ["running", "swiss", "performance"] },
  { id: "hoka", name: "HOKA", slug: "hoka", category: "clothing", description: "Maximum cushioned running shoes for trail and road with a cult following among runners.", priceRange: "$100 – $200", affiliate: "https://www.hoka.com/?utm_source=mysteryshop", tags: ["running", "cushioning", "trail"] },
  { id: "brooks", name: "Brooks Running", slug: "brooks", category: "clothing", description: "Premium running shoes engineered for performance, comfort, and injury prevention.", priceRange: "$80 – $180", affiliate: "https://www.brooksrunning.com/?utm_source=mysteryshop", tags: ["running", "performance", "comfort"] },
  { id: "zappos", name: "Zappos", slug: "zappos", category: "clothing", description: "The online shoe and clothing retailer famous for legendary customer service and free returns.", priceRange: "$20 – $500", affiliate: "https://www.zappos.com/?utm_source=mysteryshop", tags: ["shoes", "clothing", "returns"] },
  { id: "stitch-fix", name: "Stitch Fix", slug: "stitch-fix", category: "clothing", description: "Personal styling service that sends hand-picked clothing straight to your door based on your taste.", priceRange: "$20 – $300/box", affiliate: "https://www.stitchfix.com/?utm_source=mysteryshop", tags: ["styling", "personal", "subscription"] },
  { id: "frank-oak", name: "Frank And Oak", slug: "frank-and-oak", category: "clothing", description: "Sustainable menswear and womenswear brand blending modern minimalist design with eco-friendly practices.", priceRange: "$30 – $200", affiliate: "https://www.frankandoak.com/?utm_source=mysteryshop", tags: ["sustainable", "modern", "minimalist"] },
  { id: "public-lands", name: "Public Lands", slug: "public-lands", category: "outdoor", description: "Outdoor gear and apparel retailer focused on making outdoor recreation accessible to everyone.", priceRange: "$10 – $500", affiliate: "https://publiclands.com/?utm_source=mysteryshop", tags: ["outdoor", "accessible", "gear"] },
  { id: "scheels", name: "Scheels", slug: "scheels", category: "outdoor", description: "All-sports retailer and entertainment destination with massive stores carrying every sport imaginable.", priceRange: "$10 – $2,000+", affiliate: "https://www.scheels.com/?utm_source=mysteryshop", tags: ["sports", "outdoor", "multi-sport"] },
  { id: "academy-sports", name: "Academy Sports + Outdoors", slug: "academy-sports", category: "outdoor", description: "Sporting goods and outdoor recreation retailer with competitive prices on major brands.", priceRange: "$5 – $1,000+", affiliate: "https://www.academy.com/?utm_source=mysteryshop", tags: ["sports", "outdoor", "value"] },
  { id: "dicks-sporting", name: "Dick's Sporting Goods", slug: "dicks-sporting", category: "outdoor", description: "The nation's largest sporting goods retailer with gear for every sport and outdoor activity.", priceRange: "$10 – $2,000+", affiliate: "https://www.dickssportinggoods.com/?utm_source=mysteryshop", tags: ["sports", "outdoor", "fitness"] },
  { id: "peloton", name: "Peloton", slug: "peloton", category: "outdoor", description: "Interactive fitness equipment including bikes, treadmills, and rowers with live and on-demand classes.", priceRange: "$400 – $3,500+", affiliate: "https://www.onepeloton.com/?utm_source=mysteryshop", tags: ["fitness", "cycling", "home gym"] },
  { id: "bowflex", name: "Bowflex", slug: "bowflex", category: "outdoor", description: "Home gym equipment including adjustable dumbbells, resistance machines, and cardio gear.", priceRange: "$100 – $3,000+", affiliate: "https://www.bowflex.com/?utm_source=mysteryshop", tags: ["home gym", "weights", "cardio"] },
  { id: "rogue-fitness", name: "Rogue Fitness", slug: "rogue-fitness", category: "outdoor", description: "American-made fitness equipment for CrossFit, powerlifting, and functional strength training.", priceRange: "$20 – $5,000+", affiliate: "https://www.roguefitness.com/?utm_source=mysteryshop", tags: ["crossfit", "barbell", "home gym"] }
];

// Category metadata
const CATEGORIES = {
  tech: { name: "Tech", icon: "💻", description: "Computers, gadgets, electronics, and all things digital." },
  outdoor: { name: "Outdoor & Sports", icon: "🏔️", description: "Gear for hiking, camping, cycling, and outdoor adventures." },
  gifts: { name: "Gifts & Novelty", icon: "🎁", description: "Unique, personalized, and thoughtful gifts for everyone." },
  clothing: { name: "Clothing & Fashion", icon: "👕", description: "Apparel, shoes, and accessories for every style." },
  pets: { name: "Pets", icon: "🐾", description: "Food, toys, and accessories for your beloved pets." },
  gaming: { name: "Gaming", icon: "🎮", description: "Video games, consoles, collectibles, and gaming gear." },
  home: { name: "Home & Kitchen", icon: "🏠", description: "Furniture, decor, cookware, and everything for your home." }
};

function getStoreBySlug(slug) {
  return STORES.find(s => s.slug === slug) || null;
}

function getRandomStore(excludeSlug = null) {
  let pool = excludeSlug ? STORES.filter(s => s.slug !== excludeSlug) : STORES;
  return pool[Math.floor(Math.random() * pool.length)];
}

function getStoresByCategory(category) {
  return STORES.filter(s => s.category === category);
}

// Additional stores to reach 200+
STORES.push(
  // TECH
  { id: "monoprice", name: "Monoprice", slug: "monoprice", category: "tech", description: "High-quality cables, adapters, audio gear, and home theater accessories at fraction of brand-name prices.", priceRange: "$2 – $500", affiliate: "https://www.monoprice.com/?utm_source=mysteryshop", tags: ["cables", "audio", "value"] },
  { id: "iFixit", name: "iFixit", slug: "ifixit", category: "tech", description: "Repair manuals, tools, and parts for phones, laptops, and tablets. Fix your own tech and save money.", priceRange: "$5 – $200", affiliate: "https://www.ifixit.com/?utm_source=mysteryshop", tags: ["repair", "tools", "diy tech"] },
  { id: "framework", name: "Framework Laptop", slug: "framework", category: "tech", description: "Modular, repairable laptops designed to last — swap components yourself and reduce e-waste.", priceRange: "$500 – $2,000", affiliate: "https://frame.work/?utm_source=mysteryshop", tags: ["laptop", "modular", "sustainable"] },
  
  // OUTDOOR
  { id: "LL Bean", name: "L.L.Bean", slug: "llbean", category: "outdoor", description: "New England's beloved outdoor outfitter known for fleeces, boots, and gear with a legendary return policy.", priceRange: "$15 – $600", affiliate: "https://www.llbean.com/?utm_source=mysteryshop", tags: ["boots", "fleece", "camping"] },
  { id: "titleix", name: "Title Nine", slug: "title-nine", category: "outdoor", description: "Women's athletic clothing and gear designed by women for high-performance outdoor activities.", priceRange: "$20 – $250", affiliate: "https://www.titlenine.com/?utm_source=mysteryshop", tags: ["womens", "athletic", "outdoor"] },
  
  // GIFTS
  { id: "greetabl", name: "Greetabl", slug: "greetabl", category: "gifts", description: "Send personalized little gift boxes packed with treats and photos — the perfect modern care package.", priceRange: "$10 – $60", affiliate: "https://greetabl.com/?utm_source=mysteryshop", tags: ["gift boxes", "personalized", "care package"] },
  { id: "firebox", name: "Firebox", slug: "firebox", category: "gifts", description: "Wildly creative, funny, and unusual gifts for people who hate boring presents.", priceRange: "$10 – $200", affiliate: "https://www.firebox.com/?utm_source=mysteryshop", tags: ["unusual", "funny", "creative"] },
  
  // CLOTHING
  { id: "unbound", name: "Unbound Merino", slug: "unbound-merino", category: "clothing", description: "Merino wool travel clothing that packs light, resists odor, and looks great on day one or day ten.", priceRange: "$60 – $200", affiliate: "https://www.unboundmerino.com/?utm_source=mysteryshop", tags: ["merino wool", "travel", "packing light"] },
  { id: "orvis", name: "Orvis", slug: "orvis", category: "clothing", description: "Classic American fly fishing gear, hunting apparel, and dog-friendly lifestyle products.", priceRange: "$30 – $600", affiliate: "https://www.orvis.com/?utm_source=mysteryshop", tags: ["fly fishing", "hunting", "dogs"] },
  
  // PETS
  { id: "healthypaws", name: "Healthy Paws Pet Insurance", slug: "healthy-paws", category: "pets", description: "Comprehensive pet health insurance covering accidents, illnesses, and emergency care for dogs and cats.", priceRange: "$25 – $100/month", affiliate: "https://www.healthypawspetinsurance.com/?utm_source=mysteryshop", tags: ["insurance", "health", "coverage"] },
  { id: "earthbath", name: "Earthbath", slug: "earthbath", category: "pets", description: "Natural, earth-friendly pet grooming products made with safe ingredients and no harsh chemicals.", priceRange: "$8 – $30", affiliate: "https://earthbath.com/?utm_source=mysteryshop", tags: ["grooming", "natural", "shampoo"] },
  
  // GAMING
  { id: "zatu", name: "Zatu Games", slug: "zatu-games", category: "gaming", description: "Massive UK board game retailer with thousands of titles from gateway games to hardcore strategy.", priceRange: "$10 – $150", affiliate: "https://www.zatugames.com/?utm_source=mysteryshop", tags: ["board games", "tabletop", "strategy"] },
  { id: "indiemerchaisle", name: "Indie Boards & Cards", slug: "indie-boards-cards", category: "gaming", description: "Publisher of award-winning indie card and board games including The Resistance and Coup.", priceRange: "$15 – $50", affiliate: "https://www.indieboardsandcards.com/?utm_source=mysteryshop", tags: ["card games", "indie", "party games"] },

  // HOME
  { id: "magnolia", name: "Magnolia", slug: "magnolia", category: "home", description: "Joanna Gaines' home goods brand with warm, farmhouse-inspired furniture, decor, and kitchen items.", priceRange: "$15 – $1,500", affiliate: "https://www.magnolia.com/?utm_source=mysteryshop", tags: ["farmhouse", "decor", "joanna gaines"] },
  { id: "arhaus", name: "Arhaus", slug: "arhaus", category: "home", description: "Handcrafted furniture using responsibly sourced materials — quality heirlooms for the modern home.", priceRange: "$200 – $6,000+", affiliate: "https://www.arhaus.com/?utm_source=mysteryshop", tags: ["handcrafted", "furniture", "sustainable"] },
  { id: "schoolhouse", name: "Schoolhouse", slug: "schoolhouse", category: "home", description: "American-made lighting, hardware, and home goods with timeless, thoughtful craftsmanship.", priceRange: "$30 – $800", affiliate: "https://www.schoolhouse.com/?utm_source=mysteryshop", tags: ["lighting", "hardware", "american made"] },
  { id: "rejuvenation", name: "Rejuvenation", slug: "rejuvenation", category: "home", description: "Period-appropriate lighting, hardware, and house parts for home restoration and renovation.", priceRange: "$25 – $1,000", affiliate: "https://www.rejuvenation.com/?utm_source=mysteryshop", tags: ["lighting", "restoration", "hardware"] },
  { id: "burke-decor", name: "Burke Decor", slug: "burke-decor", category: "home", description: "Curated home furnishings and decor from hundreds of top brands in one beautifully designed shop.", priceRange: "$20 – $3,000", affiliate: "https://www.burkedecor.com/?utm_source=mysteryshop", tags: ["curated", "decor", "furnishings"] }
);
